version: "3.9"

services:
  db:
    container_name: "db_my_library"
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=my-library
      - POSTGRES_PASSWORD=admin

volumes:
  db_data:

